CREATE TABLE IF NOT EXISTS public.Hall (
  id bigint NOT NULL GENERATED ALWAYS AS IDENTITY (START 1 INCREMENT 1) PRIMARY KEY,
  name CHARACTER VARYING(60) NOT NULL,
  count_rows INTEGER NOT NULL,
  row_capacity INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS public.Movie (
  id bigint NOT NULL GENERATED ALWAYS AS IDENTITY (START 1 INCREMENT 1) PRIMARY KEY,
  name CHARACTER VARYING(60) NOT NULL,
  description CHARACTER VARYING(2048) DEFAULT NULL,
  reasons_to_view CHARACTER VARYING(2048) DEFAULT NULL,
  facts CHARACTER VARYING(2048) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS public.Screening (
  id bigint NOT NULL GENERATED ALWAYS AS IDENTITY (START 1 INCREMENT 1) PRIMARY KEY,
  id_hall INTEGER NOT NULL REFERENCES Hall (id),
  id_movie INTEGER NOT NULL REFERENCES Movie (id),
  showing_time TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS public.Ticket (
  id bigint NOT NULL GENERATED ALWAYS AS IDENTITY (START 1 INCREMENT 1) PRIMARY KEY,
  id_screening INTEGER NOT NULL REFERENCES Screening (id),
  row INTEGER NOT NULL CHECK (row > 0),
  seat INTEGER NOT NULL CHECK (seat > 0),
  cost FLOAT NOT NULL CHECK (cost > 0)
);

CREATE TABLE IF NOT EXISTS public.Tag (
  id bigint NOT NULL GENERATED ALWAYS AS IDENTITY (START 1 INCREMENT 1) PRIMARY KEY,
  name CHARACTER VARYING(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.Tags (
  id bigint NOT NULL GENERATED ALWAYS AS IDENTITY (START 1 INCREMENT 1) PRIMARY KEY,
  id_movie INTEGER NOT NULL REFERENCES Movie (id),
  id_tag INTEGER NOT NULL REFERENCES Tag (id)
)

