version: '3'
services:

  db:
    container_name: db
    image: postgres:15.3
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pgpasswd
      - POSTGRES_DB=cinema
    ports:
      - "5433:5432"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
